### ISSUE TITLE
Endpunkt Impfzertifikatsimulator

### ISSUE THREAD

**Issue by TH-Pega** [Digitaler-Impfnachweis/certification-apis#117]
### Discussed in https://github.com/Digitaler-Impfnachweis/certification-apis/discussions/90

<div type='discussions-op-text'>

<sup>Originally posted by **TH-Pega** June 14, 2021</sup>
Wie lautet der Endpunkt des Impfzertifikatsimulators im Internet (für Variante 1 der Anlage 12.1)?</div>

**Comment by oliver-steinbrecher** [comment]
Please see https://github.com/Digitaler-Impfnachweis/certification-apis/discussions/14
