### ISSUE TITLE
Missing trim on text fields

### ISSUE THREAD

**Issue by michaelkleinhenz** [Digitaler-Impfnachweis/certification-apis#128]
It looks like `fn`, `gn`, `fnt` and `gnt` fields are not trimmed when creating the certificate. 

Decoding a known valid certificate (created using the production path) results in the data:
```
nam: {
        fn: 'Kleinhenz',
        gn: 'Michael ',
        fnt: 'KLEINHENZ',
        gnt: 'MICHAEL'
      },
```
(note the extra blank on the `gn` value). This does not appear on the test data certificates.

**Comment by michaelkleinhenz** [comment]
Note: this is probably the wrong repo for this issue, but it looks like the backend is not open sourced (which is a bummer).

**Comment by rampage128** [comment]
This issue seemingly also causes the covpass app to not combine two vaccination certificates (first and second shot) together.

I have a trailing space in the last name in one of my certificates and now the app has two entries on the main screen and one shows "Incomplete".

**Comment by michaelkleinhenz** [comment]
This issue may be caused by using a mobile device for creating the certificates from the issuing org (like a pharmacy). Mobile text field input assist features may cause this extra blank.

**Comment by thinkberg** [comment]
The next release will fix this issue.

**Comment by thinkberg** [comment]
Der Issue ist inzwischen schon gefixt.
