### ISSUE TITLE
Example EU Digital Covid Vaccination Certificate (DE)

### ISSUE THREAD

**Issue by MikeMcC399** [Digitaler-Impfnachweis/certification-apis#137]
Will you publish an example of the EU Digital Covid Vaccination Certificate (DE) / EU digitales COVID-Impfzertifikat (DE) in PDF format here?

Is the layout available in source code anywhere for inspection?

There is a suggestion in https://github.com/corona-warn-app/cwa-documentation/issues/644 to move the QR code so it is less susceptible to printing issues. I couldn't see an appropriate place in the https://github.com/Digitaler-Impfnachweis organization to add this. Perhaps you could advise if you are open to suggestions?

**Comment by oliver-steinbrecher** [comment]
@thinkberg can you Support here?

**Comment by MikeMcC399** [comment]
https://github.com/Digitaler-Impfnachweis/certification-apis/commit/c64f85f1c4e5108625e815bed63918680caaa076 has added templates in svg format (see also https://github.com/Digitaler-Impfnachweis/certification-apis#print-templates) so this question is now effectively answered.

**Comment by thinkberg** [comment]
The changes will take effect later this week as they just went though official approval and are now being integrated into the web frontend as well as the backend pdf generation. They have been published here for software developers generating their own PDF.

**Comment by vaubaehn** [comment]
@thinkberg Thanks a lot for implementing suggested enhancements! ❤️
