### ISSUE TITLE
Authentication with client-certificate (mTLS)

### ISSUE THREAD

**Issue by ahatzifotiou** [Digitaler-Impfnachweis/certification-apis#152]
Hallo zusammen,

wir entwickeln eine Software für eine Arztpraxis. Wir möchten uns via Zertifikat authentifizieren, das RKI oder die KV weiß leider nicht wo wir dieses Zertifikat anfordern können.

Kann uns hier jemand weiterhelfen? 

Vielen Dank

**Comment by thinkberg** [comment]
Arbeiten Sie ueber RU/PU der TI oder unabhaengig davon?

**Comment by ahatzifotiou** [comment]
Wir wollen dies unabhängig von der TI entwickeln. Laut Dokumentation ist dies möglich.

**Comment by thinkberg** [comment]
Die Mail fuer Zertifikatsaussteller: https://digitaler-impfnachweis-app.de/faq/
