### ISSUE TITLE
Usage of public Trust List API

### ISSUE THREAD

**Issue by SebastianKluge** [Digitaler-Impfnachweis/certification-apis#153]
We are currently implementing our own validation service for DCC within a commercial application for access systems. Can we use the public endpoint for Ubirch's trustlist (https://de.dscg.ubirch.com/trustList/DSC/)? Are there any future restrictions in this context? Will this endpoint be secured with dedicated access data in the future?

**Comment by oliver-steinbrecher** [comment]
The Endpoint is meant be public without no security restrictions. We've implemented a rate-limiting.

**Comment by SebastianKluge** [comment]
@oliver-steinbrecher Thanks for the answer. How is the rate limit defined?

**Comment by mheicke** [comment]
@SebastianKluge this is something we currently also want to work on - if this is interesting for you, feel free to send me a message to the email address on my profile and we bundle our efforts :)

**Comment by oliver-steinbrecher** [comment]
What kind of use cases are you going to build? For large scale applications please consider your own content delivery network

**Comment by SebastianKluge** [comment]
@oliver-steinbrecher Can you please answer my question as to how the limit is defined?

**Comment by oliver-steinbrecher** [comment]
The trustlist API does not have any rate limits - remaining certificate issuing apis do have limits.

**Comment by btmpn** [comment]
One question regarding the trustlist endpoint:
as mentioned [here](https://github.com/Digitaler-Impfnachweis/certification-apis/blob/master/dsc-update/README.md#data-schema), the trustlist is prepended by a signature.

To verify the integrity of the trustlist data (json content), it must be SHA256 hashed, then signed with ECDsa using prime256v1, then converted to a base64 string.

Is this correct?
I tried it with c#, but I don't get the same value compared to the signature in the first line.

Are there any examples in C#?

**Comment by thinkberg** [comment]
1. take the first line (its the signature), decode it with base64 and keep ready for step 3
2. hash the content of the file after the first line with SHA256
3. use the public key from the root of the server and do an ECDSA verify with the hash and the signature
