### ISSUE TITLE
Array ( [curl_error_56] => OpenSSL SSL_read: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate, errno 0 )

### ISSUE THREAD

**Issue by hamidbscs8** [Digitaler-Impfnachweis/certification-apis#172]
Hi,
I am try to implement certification api by using Rest API, right now i am facing above issue when I run php script. 
Array ( [curl_error_56] => OpenSSL SSL_read: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate, errno 0 )

Can anyone help me please.

**Comment by oliver-steinbrecher** [comment]
API Requires a client-certificate which need to be officially requested.
