### ISSUE TITLE
Wrong links in “DCC Certificate of Recovery“, ”DCC Test Certificate“ and “DCC Vaccination Certificate” ...

### ISSUE THREAD

**Issue by Jo-Achim** [Digitaler-Impfnachweis/certification-apis#176]
Actually the links “DCC Certificate of Recovery“, ”DCC Test Certificate“ and “DCC Vaccination Certificate” in README.md under https://github.com/Digitaler-Impfnachweis/certification-apis/tree/master/templates are wrong: error 404.

**Comment by thinkberg** [comment]
Template links have been fixed.
