### ISSUE TITLE
Certificate issuing using PDF returns empty PDF

### ISSUE THREAD

**Issue by iseks** [Digitaler-Impfnachweis/certification-apis#181]
We try to use api.impfnachweis.info/api/certify/v2/issue to generate PDF certificates after receiving an an access token following the TI infrastructure authentication workflow. 

Using Accept=[application/pdf] we receive a valid response [status=200] including a formally valid pdf file. However, the pdf file appears to be a single blank page: [TestCert.pdf](https://github.com/Digitaler-Impfnachweis/certification-apis/files/7006706/TestCert.pdf)

In contrast, if we use Accept=[application/cbor+base45], we receive a QR-code (HC1:6BFOXN*TS0BI$ZD8UHE.HMM9Y5S4MJ*G2.GP1WG%MP8*I5J5:8K-%7.HLIIJS:E...).

Is there any idea, why we receive a blank PDF page, although the cbor QR code seems to be valid?

**Comment by Programmat0r** [comment]
Hi i had the same issue. 
In my case the solution was to write the PDF content right at the moment when i receive it:

   var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
   
                using (var stream = File.Create(filename))
                    httpResponse.GetResponseStream().CopyTo(stream);

I hope this helps you.

**Comment by iseks** [comment]
Hi Prammat0r, 

thanks for your hint. Actually we process and store the PDF content directly after reception. However, the PDF file remains to be a blank page.

 Have a nice day, Oliver

**Comment by iseks** [comment]
We solved the problem. The PDF-data in the response was correct, however some erroneous encoding conversion caused corruption of binary data, which made the PDF file to be a blank page.
