### ISSUE TITLE
Reverse process

### ISSUE THREAD

**Issue by qq5678** [Digitaler-Impfnachweis/certification-apis#193]
Hello

i already have the json data . Do you have any idea how can I reverse the process and convert the json to a QR code ?

**Comment by thinkberg** [comment]
> Hello
> 
> 
> 
> i already have the json data . Do you have any idea how can I reverse the process and convert the json to a QR code ? 

There is no way to reproduce the QR code if you only have the JSON. You will lack the cryptographic signature.
