### ISSUE TITLE
SMC-B Authentifizierung in Zahnarztpraxen

### ISSUE THREAD

**Issue by oliverschaefer** [Digitaler-Impfnachweis/certification-apis#205]
Durch den aktuellen Beschluss der Ministerpräsidenten vom 02.12.21 sollen zukünftig auch Zahnärzte Impfungen durchführen. 

Die Zahnarztpraxen sind ebenso wie die Arztpraxen an die TI angeschlossen und verwenden eigene SMC-Bs zur Authentifizierung. Die öffentlichen Zertifikate dieser SMC-Bs enthalten jedoch nicht den notwendigen Eintrag "Betriebsstätte Arzt". 

Hier sollte das Backend kurzfristig auch den Eintrag "Zahnarztpraxis" mit der ProfessionOID "1.2.276.0.76.4.51" akzeptieren, um die Ausstellung von Impfnachweisen in den Zahnarztpraxen zu ermöglichen.

**Comment by oliver-steinbrecher** [comment]
Nehmen wir mit in die Klärung und weiteren Sicherheitsprüfung.

**Comment by oliverschaefer** [comment]
@oliver-steinbrecher Danke. Ich setze es mir mal in einer Woche auf Wiedervorlage ;-)

**Comment by oliverschaefer** [comment]
@oliver-steinbrecher gibts schon was neues?

**Comment by oliver-steinbrecher** [comment]
Das Thema ist vorbereitet und wartet auf die finale Verabschiedung.

**Comment by oliverschaefer** [comment]
@oliver-steinbrecher Ist die Sache schon verabschiedet? Wenn nein, wie ist denn da die zeitliche Planung?

**Comment by oliver-steinbrecher** [comment]
Das Thema wartet immer noch auf eine Freigabe. Es gibt politische Umwegsamkeiten. Technisch könnten wir sofort loslegen

**Comment by Nilihasi** [comment]
@oliver-steinbrecher @oliverschaefer Laut IFG ist seit sechs Wochen alles geregelt ? Es kann ja nur an technischen Umwegsamkeiten liegen ?!

**Comment by oliverschaefer** [comment]
@oliver-steinbrecher Gibt es Neuigkeiten aus der Politik?

**Comment by oliver-steinbrecher** [comment]
Ich kann leider kein Update geben.

**Comment by oliver-steinbrecher** [comment]
Das Thema gewinnt nun wieder an Fahrt. @oliverschaefer können Sie einmal schilden, wie eine Nutzung aus der Zahnarztpraxis genauer aussehen würde ? Genauer, welche Anwendungen bzw. Integration eine Rolle spielen?

**Comment by oliverschaefer** [comment]
@oliver-steinbrecher im zahnärztlichen Bereich sind aktuell etwa 10-20 verschiedene PVS Hersteller vertreten. Bis diese die Codeerstellung flächendeckend integrieren, würden Monate vergehen. Die Webanwendung des RKI setzt momentan einen Login über die KVen voraus, nicht jedoch über die KZVen. Auch hier müssten sicher Schnittstellen zeitaufwändig abgestimmt werden. Die Desktop-Apps des RKI hingegen, wären sofort einsatzbereit und auch für die Ärzte bereits mit entsprechenden Anleitungen verfügbar. Für weitere Details können wir gern telefonieren

**Comment by Nilihasi** [comment]
Ergänzen möchte ich, bei Verwendung der Desktop_APP die Verbindungsprüfung über die bestehende Telematikstruktur funktioniert. Es kommt dann lediglich bei der Anmeldung zum Error #1103

**Comment by oliver-steinbrecher** [comment]
Wir werden es sehr zeitnah freischalten sobald es aktiv nutzbar ist , informiere ich hier.

**Comment by oliver-steinbrecher** [comment]
Wir haben den Feldtest gestartet. Für eine Teilnahme am Feldtest kann man sich bei der Adresse dcc-support@ubirch.com und dem Betreff "Teilnahme am Feldtest Anbindung Zahnärzte an DCC über TI" melden.

**Comment by oliverschaefer** [comment]
@oliver-steinbrecher Vielen Dank für die Info, ich habe eine Mail geschickt

**Comment by oliverschaefer** [comment]
@oliver-steinbrecher Der Funktionstest soeben war erfolgreich. Damit könnte dieses Ticket geschlossen werden. Der Ordnung halber müsste SMCB-Authentication.md allerdings noch angepasst werden
