### ISSUE TITLE
Clarification for which use case which app must be used for scanning (print PDF)

### ISSUE THREAD

**Issue by iseries** [Digitaler-Impfnachweis/certification-apis#206]
See: https://github.com/corona-warn-app/cwa-app-android/issues/4468

**Comment by thinkberg** [comment]
I have forwarded this for decision making.

**Comment by iseries** [comment]
regardless of the fact that this article is poorly researched, the urgency with which app one should scan is explained again here. Many didn’t always understand it.

https://www1.wdr.de/nachrichten/rheinland/barbesitzer-deckt-sicherheitsluecke-corona-warn-app-auf-100.html?s=09

**Comment by timokoenig** [comment]
There are suggestions to adjust the app as well

https://github.com/Digitaler-Impfnachweis/covpass-android/issues/103
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/71

**Comment by oliver-steinbrecher** [comment]
We’ve added improvements in the CovPass App:
- changed labels and text to explain the difference
- Added limit for number of certificates in the app
- Hint when certificate of a different person is added
