### ISSUE TITLE
ICAO Implementation differs from test implementation

### ISSUE THREAD

**Issue by jona7o** [Digitaler-Impfnachweis/certification-apis#209]
Hi,

we are a software development company with a product for COVID19 test- and vaccination centers. For this use case we create both, vaccination certificates over ubirch/ibm api and test certificates over the cwa endpoint. Today I found a miss match between these two certificates for the same input.

I think this bug is located in the ubirch/ibm api because i think the dot char "." is not specified for a machine readable string and gets replaced by nothing and not with an "<" char. If it is defined this is a bug in the reference implementation of the cwa. I'll open these requests in both github repositorys and link each other. Could someone clarify which implementation is correct?

**Example for Vaccination certificates with Ubirch/IBM API:**
"fn": "Dr. Mustermann",
"gn": "Max",
"fnt": "DR<<MUSTERMANN",
"gnt": "MAX"
 
**Example for Test over CWA API**
"fn": "Dr. Mustermann",
"gn": "Max",
"fnt": "DR<MUSTERMANN",  
"gnt": "MAX" 

Regards, Tobias

https://github.com/corona-warn-app/cwa-quicktest-onboarding/issues/68

**Comment by vaubaehn** [comment]
Hi @jona7o ,

I'm following issues with ICAO transliterations as it causes problems when there's a mismatch of associating DCCs to one person by their standardized names.
I'm a bit late with my question, but would be happy if you replied:
You are writing that you're creating test certificates via the CWA API. I assume you are referring to the backend of TSI's Schnelltestportal? If yes, then you coded the ICAO transliteration yourself I guess?
When you are referring to
> reference implementation of the cwa

what do you mean concretely?

Your repsonse could help to move on in the issue of harmonizing ICAO transliterations across different implementations in the overall-workflow of DCCs associated with TSI (RAT portal & backend API partners, Ubirch): https://github.com/corona-warn-app/cwa-quick-test-frontend/issues/185#issuecomment-1021142950

Thanks very much in advance,
v.
