### ISSUE TITLE
Date Format and additional information like boost or recov

### ISSUE THREAD

**Issue by ManuelB** [Digitaler-Impfnachweis/certification-apis#211]
When creating certificates on the official Robert Koch Institut Portal it is possible to select a german date time format and to add some additional information like boost or recov.

Here is a screenshot of the correspondig part:
![Bildschirmfoto von 2021-12-16 10-44-13](https://user-images.githubusercontent.com/457641/146347705-6821f03a-05ee-4096-91ee-a718de35848d.png)

I was not able to find any information about how to do this with the DGC REST interface. Is this also possible with the given REST interface?

**Comment by thinkberg** [comment]
Its a speciality of the frontend to render this extra text. As the frontend renders the PDF it has some freedom to add text. The API does not have a distinction for booster.

**Comment by jleufgen** [comment]
@ManuelB do you need any more information on this? Otherwise we can close this ticket :-)

**Comment by ManuelB** [comment]
@jleufgen it would be nice if I can add this as a feature request for a future api nevertheless feel free to close this issue if not action will be taken. If you open source the backend I can also send you a pull request to add these features on my own.

**Comment by thinkberg** [comment]
The boost addendum will be remove in the next release of the frontend. The date format is actually a bug from my point of view, as the DCC is an international document and should have the YYYY-MM-DD format, not a the German way of writing.
