### ISSUE TITLE
Folding instruction missing on vac certs

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/certification-apis#212]
The print-out-template for vac certs is missing the folding instruction, which exist on test and recovery certificate print outs.

Compare https://github.com/Digitaler-Impfnachweis/certification-apis/blob/master/templates/VaccinationCertificateTemplate_v4.1.svg to https://github.com/Digitaler-Impfnachweis/certification-apis/blob/master/templates/RecoveryCertificateTemplate_v4.1.svg.

I recommend to add the folding instructions to the vac cert template too.

**Comment by JDoodsCGM** [comment]
Dear sender,

CGM is temporarily not reachable in some regions via the usual eMail addresses and landline numbers.  In these cases, please feel free to use SMS and mobile telephony of your individual contact persons, as far as they are known to you or inform yourself about further contact possibilities via the respective company or product page.  

Thank you for your understanding and best regards, 
Your CGM Team  

-------------------------

Sehr geehrte Absenderin, 
sehr geehrter Absender,

CGM ist in einigen Regionen vorübergehend nicht über die gewohnten eMail-Adressen und Festnetznummern erreichbar.  Bitte nutzen Sie gerne in diesem Fall SMS und Mobilfunk-Telefonie Ihrer individuellen Ansprechpartner, soweit diese ihnen bekannt sind oder informieren Sie sich über die jeweilige Firmen- bzw. Produktseite über weitere Kontaktmöglichkeiten. 

Vielen Dank für Ihr Verständnis und freundliche Grüße,  
Ihr CGM-Team

**Comment by Ein-Tim** [comment]
Is this repository managed or in any form related to CGM? If not, this comment should definitely not be posted on every new issue created here O:

**Comment by timokoenig** [comment]
@Ein-Tim not that I know of

@oliver-steinbrecher can you help here and please remove the comment?

**Comment by timokoenig** [comment]
I think the folding instructions got omitted because of the amount of text on the vaccination certificate. Maybe the instructions can be added smaller in a different spot

**Comment by Ein-Tim** [comment]
@timokoenig 

Yes, this would be great!

**Comment by oliver-steinbrecher** [comment]
> Is this repository managed or in any form related to CGM? If not, this comment should definitely not be posted on every new issue created here O:

I removed it

**Comment by oliver-steinbrecher** [comment]
We're not planning to adjust this.
