### ISSUE TITLE
Adjust issuance portal to new EU standard for booster vaccination after 1/1 basic immunization

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/certification-apis#214]
The EU decided the following:

"In addition, today the Commission has also adapted the rules for the encoding of vaccination certificates. This is necessary to ensure that vaccination certificates showing completion of the primary series can always be distinguished from vaccination certificates issued following a booster dose.

Boosters will be recorded as follows:

- 3/3 for a booster dose following a primary 2-dose vaccination series.
- **2/1 for a booster dose following a single-dose vaccination or a one dose of a 2-dose vaccine administered to a recovered person**." 

See https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837

The issuance portal should be adjusted to this new standard.

**Comment by oliver-steinbrecher** [comment]
Thanks for pointing out this topic. We're working on this . All Systems are going to be adjusted at the beginning for February

**Comment by oliver-steinbrecher** [comment]
Closing this because it's planed to be delivered in time

**Comment by Ein-Tim** [comment]
@oliver-steinbrecher 

Okay, thanks for the feedback.
