### ISSUE TITLE
Dokumentation der mTLS-Authentifizierung & Testmöglichkeiten

### ISSUE THREAD

**Issue by adewes** [Digitaler-Impfnachweis/certification-apis#217]
Aktuell gibt es keine genaueren Informationen über die mTLS-Authentifizierung. Gibt es hierzu schon Dokumentation? Existiert eine Möglichkeit das auf der Staging-/Test-Infrakstuktur zu testen? Anlass ist ggf. die Integration in die [Kiebitz Open-Source Software für Impfterminvermittlung](https://github.com/kiebitz-oss). Die zu nutzende API ist ja gut dokumentiert, allerdings sehe ich keine Möglichkeit Test-Credentials zu generieren, übersehe ich da etwas?

**Comment by thinkberg** [comment]
Es koennen Credentials fuer die Nutzung der Testumgebung ueber dcc-support@ubirch.com angefragt werden.

**Comment by adewes** [comment]
Hey @thinkberg, I sent an e-mail to the address but haven't received a reply all week. Is this normal? Just want to make sure the mail didn't get lost.

**Comment by thinkberg** [comment]
Soweit ich das sehen kann ist geantwortet worden. Ist die Mail eventuell im Spam gelandet?
