### ISSUE TITLE
Johnson & Johnson + Moderna Booster (2 von 1) funktioniert nicht.

### ISSUE THREAD

**Issue by kaplan81** [Digitaler-Impfnachweis/certification-apis#229]
Liebes Dev Team,

Erstens herzlichen Glückwunsch für dieses Projekt.

Zweitens solle ich bieten, dass Sie mein Deutsch entschuldigen. Ich komme aus Spanien, aber ich wohne in Berlin.

Ich wurde letztes Jahr mit J&J geimpft. Vor 2 Wochen habe ich meinen Moderna Booster gekriegt.

Bei der CovPass App, wenn ich in meinem neuen Zertifikat anschaue, steht es da, auf "Nummer der Impfung/Dose number", "2/1". Ich habe doppelt bekommen, weil ich mit J&J geimpft wurde.

Das Problem is, wenn jemand meinen QR Code scannt, bekommen wir eine rotte Warning. Die sagt: "3G. Vaccinated (2/1).  08.02.2022. 16 days ago".

Ich hoffe, das ist ein Bug. Ich kann nicht mehr geimpft werden, und ich muss auf jeden Fall, ein normales Leben führen.

Ich füge ein Bild bei.

Danke im Voraus.
![covpass-red-flag](https://user-images.githubusercontent.com/12369243/155491714-1a50dde0-351b-4dbc-b3cb-c8612039f7d9.jpeg)

**Comment by oliver-steinbrecher** [comment]
Haben Sie ihr Zertifikat mit der CovPass-Check App geprüft ?
