### ISSUE TITLE
Authorization token needed for "/api/certify/v2/issue" endpoint?

### ISSUE THREAD

**Issue by rlaveaux** [Digitaler-Impfnachweis/certification-apis#26]
According to the documentation of the API this endpoint requires a JWT authentication token.

But the CURL examples do not show the use of such a token.
When I test the API, it works fine without an access token.

- Is this a mistake in the documentation?
- If an access token will be required in the future, then where can I find the documentation for that?

**Comment by thinkberg** [comment]
The JWT token is required only for use via TI network. This has been updated in the OpenAPI specification now.
