### ISSUE TITLE
Decoding the example code

### ISSUE THREAD

**Issue by SephGER** [Digitaler-Impfnachweis/certification-apis#44]
Hi. I already have a base45 decoder working with the text examples of https://datatracker.ietf.org/doc/draft-faltstrom-base45/
How do I decode the QR-Code to the CBOR-Object. I have tried to put the `:6BF[...]` into various zlib-deflaters after decoding it with base45 as told in paragraph 2.2 of the https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v3_en.pdf but I dont get the CBOR-Object.

**Comment by SephGER** [comment]
[example_decoded.txt](https://github.com/Digitaler-Impfnachweis/certification-apis/files/6563414/example_decoded.txt)

**Comment by SZoerner** [comment]
Hey @SephGER.
There are a couple of things involved when decoding a Digital Covid Certificate (DCC), but in general, the final QR Code is encoded as:
-  JSON->CBOR->COSE->Zlib->Base45 = QR.

[This schematic](https://github.com/ehn-digital-green-development/hcert-spec#overview) visualises this quite nicely. For more specific details (HC1: prefix, error correction rate, signature algorithms,...), you might want to have a look at the [official spec for the barcode format](https://github.com/ehn-digital-green-development/hcert-spec/blob/main/hcert_spec.md#422-qr-2d-barcode).
The [eHN Github organisation](https://github.com/ehn-digital-green-development/) then also has sample implementations for decoding in various programming languages - [this python script](https://github.com/ehn-digital-green-development/ehn-sign-verify-python-trivial/blob/main/hc1_verify.py) for example implements the individual steps, but depending on your weapon (programming language) of choice, you might want to jump straight to one of the other `hcert-*` repositories. 

Hope that helps!

**Comment by SephGER** [comment]
Thanks, didn't knew about the eHN Github. This helps a lot :)
