### ISSUE TITLE
ProfessionOID "Öffentliche Apotheke"

### ISSUE THREAD

**Issue by dhufnagel** [Digitaler-Impfnachweis/certification-apis#80]
Will the SMB-C authentication flow also work with the ProfessionOID 1.2.276.0.76.4.54 for pharmacies?

**Comment by ManuelB** [comment]
We are interested in this aswell. Today our tests failed: https://github.com/Digitaler-Impfnachweis/certification-apis/discussions/87

But the reason was not that we were a pharmcy but that the IdP was not responding correctly.

**Comment by oliver-steinbrecher** [comment]
This is a valid question . I'll take care of clarifying this and get back to you soon.

**Comment by ManuelB** [comment]
We can confirm that is is not working for a public pharmacy: Zugriffsbedingungen nicht erfüllt

**Comment by ManuelB** [comment]
Korrektur, der Fehler kam vom Connector und man kann mit VerifyPin und PIN.SMC die SMC freischalten.

**Comment by oliver-steinbrecher** [comment]
Do you still request this support ?

**Comment by ManuelB** [comment]
@oliver-steinbrecher based on the fact that currently the DAV solution was shutdown based on security issues. It makes a lot of sense to open this possibility for the pharmacies to create vaccination certificates.

**Comment by dhufnagel** [comment]
Looks like this is going to happen as consequence of the issues with the DAV Portal. Why not straight up using this approach instead of one cert fits all 👎

**Comment by ManuelB** [comment]
@dhufnagel we tried it today in a pharmacy did not work yet. I hope aswell that this interface will be opened for the pharmacies.

**Comment by dhufnagel** [comment]
@ManuelB I am referring to this article: https://www.apotheke-adhoc.de/nachrichten/detail/politik/bmg-zertifikate-erst-wieder-nach-ti-migration/
It seems that there will be no need for third party software, so this will no longer be interesting for me.

**Comment by ManuelB** [comment]
@dhufnagel I currently expect that the DAV will provide an OpenID Connect provider for all members. Probably based on Keycloak (https://www.keycloak.org/). This is how a lot of federal KV (Kassenärztliche Vereinigung) are doing it.

Our solution is using SMC-B certificates: https://github.com/ere-health/dgc-ps-app/ This would be my favorite approach. From a robustness perspective all approaches should be working at the same time.

**Comment by jleufgen** [comment]
Hi all, a change of the registration procedure is currently not planned. Best regards!
