### ISSUE TITLE
Deviating calculation full protection in apps

### ISSUE THREAD

**Issue by elgohr** [Digitaler-Impfnachweis/certification-apis#91]
Due to the fact that the code of the apps isn't open sourced, this issue resides here.
The computation of the time for "total protection at" defers between iOS and Android by 1 day. It looks like the iOS app takes the `vaccination date + n weeks` and the Android the `vaccination date + n weeks + 1`

**Comment by MikeMcC399** [comment]
The CovPass-App FAQ on https://digitaler-impfnachweis-app.de/faq/ from the Robert Koch-Institut says:
 
"**Warum ist der QR-Code als Nachweis für den vollständigen Impfschutz erst nach 14 Tagen gültig?**

Der volle Corona-Impfschutz ist erst 14 Tage nach der letzten erforderlichen Impfung erreicht. Der QR-Code als Nachweis für den kompletten Impfschutz ist daher erst ab Tag 15 nach der vollständigen Corona-Impfung gültig."

This seems to agree with https://www.bundesanzeiger.de/pub/publication/x6tHxtuQ0pora3FnUEG/content/x6tHxtuQ0pora3FnUEG/BAnz%20AT%2008.05.2021%20V1.pdf?inline as I mentioned in https://github.com/corona-warn-app/cwa-documentation/issues/638#issuecomment-860655241.

**Comment by elgohr** [comment]
Closing this in favor of https://github.com/corona-warn-app/cwa-documentation/issues/638
Look's like at least one app has a bug 🙂
