### ISSUE TITLE
Scenario of 1 Vaccination after Covid recovery covered?

### ISSUE THREAD

**Issue by naibaf0** [Digitaler-Impfnachweis/certification-apis#94]
Does the currently released version cover the case, where a person received just one vaccination after >6 months of an Covid infection for full protection under the German guidelines.

Or will this be covered in a future release?

**Comment by oliver-steinbrecher** [comment]
Release 1.3 will over this and will be released soon.

**Comment by naibaf0** [comment]
Okay, great. Thanks for the response!

To clarify/double-check, I couldn't figure it out looking at the code / documentation on various websites regarding the API/apps. In what way will this be reflected in a certificate(s)?

From https://ec.europa.eu/commission/presscorner/detail/en/qanda_21_2781

> I have recovered from COVID-19 and my Member State has decided to only offer one dose of a two-dose vaccine to me. Will I be able to benefit from the Digital COVID Certificate?

> It is for Member States to decide whether to administer only one dose of a two-dose vaccine to recovered persons. Where they do so, the vaccination certificate should indicate that the vaccination course has been completed following the administration of one dose.
> The Commission has proposed that people who have received a single dose of a two-dose vaccine after having previously been infected with COVID-19 should be considered fully vaccinated for the purpose of travel.

I understand that with the update the option comes for digital certification of recovery. Will one of those be necessary in this case, To my understanding the certificate of recovery has an expiration date, presumably the 6 months one counts as "recovered".

Or will one be issued a "normal" vaccine certificate just with a changed number of required doses, meaning e.g. "Astrazeneca, 1/1 dose". (And this is not possible right now?)

**Comment by MapeRiptide** [comment]
Adding to ask and clarify question: Is there still "vollständiger Impfschutz" if the positive PCR test is more than 6 months ago + one only received one dose of vaccine?

**Comment by naibaf0** [comment]
@MapeRiptide Yes, according to the recommendations by German StiKo/RKI. Or the quote that I posted above... That is the grounds for my question in general, that this scenario exists but is not yet implemented or it is not clear how the process would look for e.g. an apothecary to certify this.

But questions regarding the regulations are probably better directed at the government or your local doctor and have not much to do with this implementation

**Comment by Ein-Tim** [comment]
@oliver-steinbrecher

> Release 1.3 will over this and will be released soon.

Could you elaborate how version 1.3 has improved this?

**Comment by marco79cgn** [comment]
According to my pharmacist it's not yet possible for them to generate a digital certificate out of a recovery attestation paper. This should be possible by the end of June. 
So unless you already have one you can't take advantage of version 1.3, correct?

**Comment by Ein-Tim** [comment]
The [FAQ](https://www.digitaler-impfnachweis-app.de/faq/#die-aktuell-h-ufigsten-fragen) now says under 
"Ich habe als Genesener eine einmalige „Genesenenimpfung" bekommen. Wie kann ich meine vollständige Immunisierung nachweisen?"

this:

> Wenn Sie eine Infektion mit dem Coronavirus SARS-CoV-2 durchgemacht haben und danach einmalig mit einem COVID-19-Impfstoff geimpft wurden, gelten Sie als vollständig immunisiert.

> Scannen Sie den QR-Code Ihres digitalen Corona-Impfzertifikats mit der CovPass-App. 15 Tage nach der Impfung zeigt die App einen vollständigen Schutz an.

> Wichtig: Auf Ihrem digitalen Impfzertifikat muss bei „Erstimpfung/Wiederimpfung: 1/1“ eingetragen sein. Nur dann kann die App einen vollständigen Impfstatus anzeigen.

> Sie erhalten das digitale Corona-Impfzertifikat in Apotheken, Arztpraxen oder Impfzentren, wenn Sie zusammen mit dem Gelben Impfpass oder der Impfbescheinigung einen positiven PCR-Test oder ein gültiges Genesenenzertifikat vorlegen.

**Comment by MapeRiptide** [comment]
Thanks @Ein-Tim for the headsup. Sounds too good to be true. Will check tomorrow with the pharmacy and report back here.

**Comment by MapeRiptide** [comment]
Went to 3 pharmacies in Berlin today. All said it's "currently not possible".

**Comment by thinkberg** [comment]
In Berlin: Go to the Arena vaccination center. They have a special helpdesk for these cases. Currently no extra appointment necessary.

**Comment by naibaf0** [comment]
Thanks for the update @MapeRiptide 

It's really a shame that this has been so unclear and not well communicated and documented how and when this is or will be possible.

I heard from people as of last week that they just got issued certificates with 2/2 vaccinations confirmed when they only received one as a recovered. And on the other hand my pharmacist was convinced that even recovered people need 2 vaccinations and wouldn't do anything except a 1/2 cert.

I now contacted the doctor's praxis that vaccinated me, waiting if they respond to my email and are able/willing to issue a certificate.

**Comment by MapeRiptide** [comment]
The pharmacy backend looks like this. It's not possible. ![image](https://user-images.githubusercontent.com/74463713/124492744-2be24400-ddb5-11eb-9863-13c36c1346db.jpeg)

**Comment by MapeRiptide** [comment]
> In Berlin: Go to the Arena vaccination center. They have a special helpdesk for these cases. Currently no extra appointment necessary.

Thanks for the tip. I will go there tomorrow morning and report back here. So far I didn't hear any success story so far regarding that issue.

**Comment by christianphilie** [comment]
I tried to get a 1/1 certificate in Cologne in 3 pharmacies and also at the vaccination center. All of them said their software wasn't capable to do this yet.

**Comment by marco79cgn** [comment]
> I tried to get a 1/1 certificate in Cologne in 3 pharmacies and also at the vaccination center. All of them said their software wasn't capable to do this yet.

I‘ve been trying it for weeks here in Cologne in different pharmacies (Ehrenfeld and centre). I even called my family doctor. It‘s not possible yet.

**Comment by eckertj** [comment]
Hi everyone, I was also following this topic for a while and finally got my certificate today from my doctor. They also told me, that this functionality was enabled just today for them so I guess it is currently rolled out. In case you are wondering how it looks like, I have added some screenshots of the EU certificate and how it looks in CovPass.

Also works in CWA by the way!

![eu_certificate](https://user-images.githubusercontent.com/4943203/124519564-fa37a000-dde9-11eb-97f8-4c0ca4d00636.png)
![overview-1](https://user-images.githubusercontent.com/4943203/124519568-fc016380-dde9-11eb-8ef1-b600374b290c.png)
![vaccination_cert](https://user-images.githubusercontent.com/4943203/124519574-fdcb2700-dde9-11eb-9da8-bf4f2cf53d09.png)

**Comment by rd-marco-dengel** [comment]
> Hi @eckertj!
> 
> Does your certificate starts showing the "vollstängiden Schutz" two weeks after receiving your first and only vaccine dosis? Does it have a validity of one year from the timepoint in which you were tested as positive? Or from the timepoint you were vaccinated?

Yes it does as you can see in the screenshots. 

The key point is that the certificate gets a "**Erstimpfung/Wiederimpfung: 1/1**" (→ Genesenen-Impfung). If that's the case and your vaccination date is >14 days, you get the "Vollständiger Impfschutz".

**Comment by marco79cgn** [comment]
> Hi @eckertj!
> 
> Does your certificate starts showing the "vollstängiden Schutz" two weeks after receiving your first and only vaccine dosis? Does it have a validity of one year from the timepoint in which you were tested as positive? Or from the timepoint you were vaccinated?

Yes it does as you can see in the screenshots. 

The key point is that the certificate gets a "**Erstimpfung/Wiederimpfung: 1/1**" (→ Genesenen-Impfung). If that's the case and your vaccination date is >14 days, you get the "Vollständiger Impfschutz".

**Comment by eckertj** [comment]
> > Hi @eckertj!
> > Does your certificate starts showing the "vollstängiden Schutz" two weeks after receiving your first and only vaccine dosis? Does it have a validity of one year from the timepoint in which you were tested as positive? Or from the timepoint you were vaccinated?
> 
> Yes it does as you can see in the screenshots.
> 
> The key point is that the certificate is marked as "**Erstimpfung/Wiederimpfung: 1/1**" (→ Genesenen-Impfung). If that's the case and your vaccination date is >14 days, you get the "Vollständiger Impfschutz".

Yes exactly! I only got a single shot more than 6 month after my recovery and the certificate reflects exactly this and shows me the "Vollständigen Impfschutz" (I guess >14 days after the vaccination).

According to the Corona-Warn-App, the certificate has actually a validity of one year starting from the date of the certificate creation.

**Comment by MapeRiptide** [comment]
Reporting back after a little trip to 2 more pharmacies this morning and finally a trip to a Impfzentrum.

First pharmacies: Not possible. They all use the same API Call from mein-apothekenmanager and I was invited behind the desk to take a look for myself. Maybe the devs are still rolling it out, but all interfaces look the same, like posted me from [here](https://github.com/Digitaler-Impfnachweis/certification-apis/issues/94#issuecomment-874189113): 
No chance of choosing "Erstimpfung/Wiederimpfung: 1/1" for the pharmacies.
But as @eckertj pointed it out, it is somehow possible for doctors. So I guess they are using a different portal/api to issue the documents - does anyone have intel on that? The doc who vaccinated me is on holiday so I can't check it with him right now.

Now to the Impfzentrum. After the tip from @thinkberg I went there. 
Shoutouts to "Michel" from the Impfzentrum - who took time for my case and also looked with me together into this thread to gather more information.
In theory it's not possible, because the Impfzentrum can only issue documents for people who had an appointment in one of the Impfzentrums. After some phonecalls and a little waiting time I was offered to have a special certificate, just for my case which is now showing "valid" in both Digitaler-Impfnachweis and CWA. I can't go into more details here, but for the moment I'm just happy that I can finally travel without doing any more tests. I would be happy to maybe talk to @thinkberg or one his teammembers to talk about this issue, as I don't expect everyone to be this persistent like me to finally beat german bureaucracy.

**Comment by marco79cgn** [comment]
It seems that there is currently a rollout of this feature so that at least doctors can create these certificates.

> "Um den Aufwand für Ärztinnen und Ärzte möglichst gering zu halten, soll das Ausstellen der Genesenenzertifikate – analog zu den Impfzertifikaten – ebenfalls direkt aus dem PVS möglich sein. Ein entsprechendes Software-Update soll zum 30. Juni, spätestens zum 12. Juli bereitstehen. Einige Hersteller haben den Praxen das neue Zertifikat-Modul bereits zur Verfügung gestellt." 

https://www.kbv.de/html/1150_53109.php

**Comment by SiFall** [comment]
> But as @eckertj pointed it out, it is somehow possible for doctors. So I guess they are using a different portal/api to issue the documents - does anyone have intel on that?

Based on information from [1] it seems like Impfzentren and doctors can use the webinterface (Impfzertifikatsservice) from RKI directly to issue vaccination certificates (among others), while pharmacies use the portal provided by DAV / mein-apothekenmanager. 
From information available under [2] it becomes evident that this RKI Impfzertifikatsservice should be able to also issue vaccination certificates for recovered people (Genesenen-Impfung) and recovery certificates.
Refer also to [3] to see that currently is not planned or at least currently is not known how pharmacies shall issue certificates for recovered people.

[1] https://digitaler-impfnachweis-app.de/impfzertifikat-ausstellen/
[2] https://digitaler-impfnachweis-app.de/materialien-zum-download/ / https://digitaler-impfnachweis-app.de/download/pdf/Impfpass-SNK-KV-Installationsanleitung-V2.2.pdf
[3] https://www.pharmazeutische-zeitung.de/dav-bietet-noch-keine-loesung-fuer-digitale-test-und-genesenenzertifikate-an-126544/

**Comment by marco79cgn** [comment]
> Genesene können aktuell nur in ausgewählten Arztpraxen ein digitales Zertifikat erhalten - und zwar nur, wenn die Arztpraxen "das Webportal von IBM nutzen".

https://www.tagesschau.de/inland/genesene-digitaler-impfpass-101.html

**Comment by pokkos** [comment]
It seems to be possible from tomorrow on to get the certificate in the pharmacies:
https://www.abda.de/aktuelles-und-presse/pressemitteilungen/detail/digitale-impfzertifikate-fuer-genesene-ab-morgen-in-apotheken-erhaeltlich/

**Comment by MapeRiptide** [comment]
Just saw the official announcement as well: [](https://www.pharmazeutische-zeitung.de/impfzertifikate-fuer-genesene-ab-morgen-in-der-apotheke-126777/)

I guess this issue is from tomorrow on non-existent and we can finally close this.

**Comment by christianphilie** [comment]
I can confirm that I got a 1/1 vaccination certificate at a pharmacy in Cologne today

**Comment by NicolasCGN** [comment]
> I can confirm that I got a 1/1 vaccination certificate at a pharmacy in Cologne today

Could you tell us which?

**Comment by christianphilie** [comment]
Stern-Apotheke at Waidmarkt 26 in Altstadt-Süd

**Comment by SiFall** [comment]
@NicolasCGN 
I guess you should be able to get this 1/1 certificate at any pharmacy that is issuing vaccination certificates as well (see https://www.mein-apothekenmanager.de for a list nearby). 

What I'm wondering is: does this 1/1 vaccination certificate for recovered people suffice? 
According to the Tagesschau article (https://www.tagesschau.de/inland/genesene-digitaler-impfpass-101.html) it sounds like we also additionally might need a (digital) recovery certificate:

> Wenn die Erkrankung länger zurückliegt, ist eine Impfung nötig - allerdings mit nur einer Impfdosis. Im digitalen Impfpass werden dann zwei Zertifikate vermerkt: ein Genesenen-Zertifikat und eins von der Impfung.

But I don't see how/where one would be able to obtain the digital version of the recovery proof and how somebody checking the certificate would be alerted to this. Or am I wrong and this is not mandatory? I mean you should only be able to get this 1/1 vaccination certificate for recovered people at the pharmacy if you had proof of previous recovery/infection anyways.

**Comment by MapeRiptide** [comment]
This is probably just poorly explained on the tagesschau website. You need both documents: recovery and vaccination to be able to obtain a digital QR Code Genesenenimpfungs-Zertifik at the pharmacy or doctor.

In the app there will be then only 1 certificate, which will display "vollständiger Impfschutz".
![image](https://user-images.githubusercontent.com/74463713/125100883-e33ec980-e0d9-11eb-8b97-67aa005b4bff.jpeg)

**Comment by marco79cgn** [comment]
Yes but the thing is that the app shows not a single word about your recovery afterwards. It just says „Vollständiger Impfschutz 1/1“.

**Comment by Ein-Tim** [comment]
@marco79cgn 

You have to distinguish between two things here:

1. Only COVID-Recovered: If you had a COVID infection in the last 180 days you can go to a pharmacy and they'll give you a recovery certificate ([Example](https://user-images.githubusercontent.com/67682506/125102877-0b2f2c80-e0dc-11eb-8722-3ba76d2648a6.png) - old layout).
2. If you have received a vaccination after your COVID recovery you'll get a vaccination certificate - why would it be necessary to have a separate proof of recovery & one time vaccinated? AFAIK there is no legal difference, or?

**Comment by marco79cgn** [comment]
> Only COVID-Recovered: If you had a COVID infection in the last 180 days you can go to a pharmacy and they'll give you a recovery certificate

For reasons unknown no pharmacy here could create a digital recovery certificate for me even though I have both a PCR and a letter from the Gesundheitsamt (~5 months old).

> AFAIK there is no legal difference, or?

That‘s a good question and the thing where she was not sure about. Because normally you need two vaccinations with mRNA and this certificate just says „1/1“ but not why. I guess it‘s no problem here in Germany but maybe in other countries. Afaik there are still countries in Europe where you have to get two shots even though you‘re recovered. 

We‘ll see.

**Comment by marco79cgn** [comment]
> Because normally you need two vaccinations with mRNA and this certificate just says „1/1“ but not why.

I just double checked with the CovPass app and there‘s a difference to the Corona Warn App. The latter doesn‘t say a word about Recovery but the CovPass app explains the following if you open the certificate details: 

![B45EF328-8B00-4220-BF46-92B18157108B](https://user-images.githubusercontent.com/9810829/125105936-53038300-e0df-11eb-93d0-98a2d39490f8.jpeg)

**Comment by Ein-Tim** [comment]
@marco79cgn This text will be added to the next version of the CWA too.

**Comment by SiFall** [comment]
Thanks @MapeRiptide and @marco79cgn.
I agree with @marco79cgn, @Ein-Tim pharmacies cannot issue recovery certificates, only vaccination certificates (normal ones and those 1/1 for recovered people).

From a legal standpoint I guess it could be problematic, cf. § 2 S. 1 Nr 3 b) SchAusnahmV (https://www.gesetze-im-internet.de/schausnahmv/__2.html)
> Im Sinne dieser Verordnung ist  [...] ein Impfnachweis ein Nachweis hinsichtlich des Vorliegens einer vollständigen Schutzimpfung gegen das Coronavirus SARS-CoV-2 in deutscher, englischer, französischer, italienischer oder spanischer Sprache in verkörperter oder digitaler Form, wenn die zugrundeliegende Schutzimpfung mit einem oder mehreren vom Paul-Ehrlich-Institut im Internet unter der Adresse www.pei.de/impfstoffe/covid-19 genannten Impfstoffen erfolgt ist, und [...]
> b)  bei einer genesenen Person aus einer verabreichten Impfstoffdosis besteht,

So exactly because of what @marco79cgn said
> **Because normally you need two vaccinations with mRNA** and this certificate just says „1/1“ but not why. I guess it‘s no problem here in Germany but maybe in other countries. Afaik there are still countries in Europe where you have to get two shots even though you‘re recovered.

As a recovered person you therefore may need to justify (if somebody checks this) why you only have one dose instead of the otherwise required 2 (with mRNA). And this you could only prove with a paper recovery proof or digital recovery certificate.
But I would also agree with @marco79cgn that it will probably not be a problem in Germany, but the interesting question is how this will be accepted by other EU countries.

Nonetheless from a practical perspective I'd say the 1/1 vaccination certificate should probably be sufficient because, as was said, it shows "Vollständiger Impfschutz" anways, even if there's a special note attached. So the person checking would actually need to verify the vaccine used to notice that it was mRNA and 1/1. I doubt this will be relevant in practice, especially if apps like the CovPass Check will (probably) also display "Vollständiger Impfschutz"...

**Comment by Ein-Tim** [comment]
And most important: CovPassCheck not even shows which vaccination you have received, so this would only be noticed if someone reads through the details shown in your wallet app.

**Comment by MapeRiptide** [comment]
Thanks so much for everyone chiming in here with knowledge. Is there a list which countries allow a single dose of vaccine after recovery to be recognized as "fully vaccinated"? If not I would start to compile one for everyone.

**Comment by MikeMcC399** [comment]
@MapeRiptide 
> Is there a list which countries allow a single dose of vaccine after recovery to be recognized as "fully vaccinated"? If not I would start to compile one for everyone.

The site https://reopen.europa.eu/en is attempting to list the rules in the EU from country to country. For instance Germany => Spain is on https://reopen.europa.eu/en/from-to/DEU/ESP.

It's not so clear if every country treats the "single dose of vaccine after recovery" the same, although it is just a vaccination certificate which declares one dose of a one dose series, so it is a complete vaccination certificate (after 14 days' wait), rather than a recovery certificate.

**Comment by naibaf0** [comment]
Unfortunately the "reopen europa" site seems to be lacking when it comes to our specific scenario.

E.g. both, Germany and France (i am pretty suree) allow/recommend just one dose after recovery for full vaccination, however if you check travel from either country to the other, there is no mention of it on the requirements. It is either full vaccination (2/2 or 1 in case of Johnson Johnson), or recovery.

I suspect that it is very similar regarding the information of other countries as well, if I were to go traveling I would probably check with airline/embassy or a government agency directly to be sure

**Comment by MikeMcC399** [comment]
@naibaf0 
I found https://ec.europa.eu/commission/presscorner/detail/en/qanda_21_2984 which says:

"This update was adopted by the Council on 14 June 2021.

What are the main changes introduced by the latest update of the Council Recommendation?

Fully vaccinated persons with the EU Digital COVID Certificate should be exempted from travel-related testing or quarantine 14 days after having received the last dose of a [COVID-19 vaccine approved for the entire EU](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans_en). This should also cover recovered persons having received a single dose of a 2-dose vaccine. Member States could also lift such additional restrictions after the first dose of a 2-dose series, while taking into account the impact of SARS-CoV-2 variants of concern or interest on vaccine effectiveness after the administration of only one dose."

**Comment by naibaf0** [comment]
@MikeMcC399 Nice, thanks for the info, I wasn't aware of that statement.

Anyways, I think as far as the actual issue is concerned, it can now be considered resolved.

Thanks everybody for the input!
