### ISSUE TITLE
Feature Request: Add possibility to check digital test certificates

### ISSUE THREAD

**Issue by thecloudseeker** [Digitaler-Impfnachweis/certification-apis#99]
Some european countries also provide digital test certificates. However if you want to verify these in the german CovPass Check App, it just states that the certificate is not proving a complete vaccination.

I understand that the scope of the CovPass Check-App is just to verify vaccination, but with assumed increasing travel in Europe and therefore in Germany, this feature impariety may result in confussion and problems for travellers. Thus I would propose that this feature will be included in the roadmap.

**Comment by oliver-steinbrecher** [comment]
Upcoming release is going to support test and recovery certificates in both apps.
